### ISSUE TITLE
Password issue sessman and vnc

### ISSUE THREAD

**Issue by antoinetran** [neutrinolabs/xrdp#325]
Hi,

I have this issue with xrdp 0.5.0-0.13.el6 and 0.6.1-3.el6 and tigervnc-server 1.1.0-5.el6_4.1, in Red Hat 6.5.

With LDAP account, I cannot connect to a xrdp server at the first login. At the second time, it works (only for 0.5.0, not for 0.6.1). There is no problem if I create the home dir before connecting the first time. This let me to believe there is a sleep issue between xrdp-sesman and Xvnc. The time xrdp-sesman creates ~/.vnc/sesman_$USER_passwd, and launch Xvnc, xrdp or xrdp-sesman says it cannot connect to Xvnc (127.0.0.1:591X).

Workaround:
a) Disable VNCAuth (in /etc/xrdp/sesman.ini, adds SecurityTypes to None see https://github.com/TigerVNC/tigervnc/issues/24)
b) Creates the home dir before connecting for xrdp 0.5.0 (for 0.6.1, restart xrdp too)

a) is not secure enough for us since there is a big security risk. b) does not work either because we do not know who wants to connect before creating the home dir. Trying to modify Xvnc or startwm.sh, to create the home dir, does not work because it is already too late when they are called.

What is expected:
xrdp or xrdp-sesman or libvnc.so must create the sesman_$USER_passwd, even when the home dir does not exist, then waits for it (or sleep).

Related bug tracking:
https://bugzilla.redhat.com/show_bug.cgi?id=557510
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=654788

**Comment by itamarjp** [comment]
this bug is already fixed in redhat xrdp, try a newer version 

http://koji.fedoraproject.org/koji/packageinfo?packageID=9026

I think just increasing the default value of delay_ms in xrdp.ini can avoid the issue.

See also:
neutrinolabs/xrdp#182
neutrinolabs/xrdp#196

Increasing delay_ms value is easier but I also think your patch is better than static default value of delay_ms. If an environment requires 2 seconds delay and another environment requires 5 seconds delay. Your patch will work on both environments.

**Comment by antoinetran** [comment]
Thank you for your answer.

I am trying to find the matching version where the fix has been applied. The commit is done " on 7 Nov 2014", but the latest tag is 0.8.0 on 20 May 2014. So the only way to get this fix is to compile against the devel branch? We have a system in production, so it's difficult to do that. Thank you.

**Comment by itamarjp** [comment]
http://koji.fedoraproject.org/koji/packageinfo?packageID=9026

try this one

http://koji.fedoraproject.org/koji/buildinfo?buildID=669452

**Comment by antoinetran** [comment]
I tried xrdp-0.9.0-5.fc24. It has systemd, instead of init.d. This is because of course, I have Red Hat 6 instead of 7. Even with that, starting xrdp brings me a mismatch error with glibc library. It requires 2.15, while it is and will stay at 2.12 in Red Hat 6 ([source](https://www.redhat.com/archives/rhelv6-list/2012-August/msg00015.html)). I just tried 0.6.1-4el6. The issue is still here, so this fix is not the last version for Red Hat 6.

**Comment by antoinetran** [comment]
The 0.6.1-4el6 appears to be even worse because the password file ~/.vnc/... is not created during multiple login attempts, making login fail. Restarting xrdp enable it to create this file. I don't know why.

**Comment by mvdb-christmann** [comment]
I can confirm this bug on Debian Jessie. I just built xrdp upstream version and have the exact problem as antoinetran. The server is a member of an active directory, PAM is configured to authenticate via samba/winbind and create home directories for users on their first login. This works perfectly for e.g. ssh or other services but not for xrdp. 

I had a look at bugs #182 and #196 which seem similar but have a different background. The problem of these referenced bugs is that VNC needs some time to start up before connecting to it - so a timeout (loop) has been implemented. This is not the case here. 

In this bug, VNC starts but there seems to be a problem with the order a full PAM based authentification. xrdp is supposed to first do the PAM authentication (which would initially creating a users' home directory) and then start VNC. This seems not to work as expected somehow... In general, the home directory gets created somewhen, but obviously too late in the process so that VNC spits out the error lines

```
[20160229-15:51:49] [ERROR] env_set_user: error creating .vnc dir
[20160229-15:51:49] [WARN ] can't write vnc password hash file - /home/DOMAIN/username/.vnc/sesman_username_passwd
```

If I kill the Xvnc process (or completely restart xrdp) and try it again, it works. If I create the user's home directory manually it also works.

**Comment by antoinetran** [comment]
Yes, my correction is as follow:
For Red Hat, I had to edit /etc/pam.d/xrdp-sesman and put this code below. The homedir creation is done before the pam returns.

It seems the login step takes 20 seconds more, but at least, it works even if the homedir is not created.
#%PAM-1.0
#@include common-auth
#@include common-account
#@include common-session
#@include common-password

# This is for Red Hat distributions.
auth       include      password-auth
account     required      pam_oddjob_mkhomedir.so
account    include      password-auth
session    include      password-auth

**Comment by mvdb-christmann** [comment]
My /etc/pam.d/xrdp-sesman looks like yours but without the hashes before the "@include"-lines. Are you sure about the hashes at the beginning of each line (commenting out the whole file) or is it a copy-paste error?
As I said: PAM and pam_mkhomedir works in all cases, but not for xrdp.

**Comment by antoinetran** [comment]
I don't know which distribution you have, but I have Red Hat. Red Hat does not have any common-* files, thus the comment. I believe, as written, this was for Debian.

Anyways, my correction is to put the home dir creation at the account step, and make it required, before any other sufficient rule. I could have optimized by removing the old home dir creation rule in session step, but otherwise I find this way more readeable.

**Comment by mvdb-christmann** [comment]
I tried this this one out, still using the common-blocks from Debian (but it doesn't work):

```
#%PAM-1.0

@include common-auth
account required    pam_mkhomedir.so umask=0027
@include common-account
@include common-session
@include common-password
```

Any other ideas?

**Comment by antoinetran** [comment]
I believe you would have to analyze all the PAM stack, finding at which point your PAM returns. This may indicate you have a sufficient rule in common-auth. You could try to put the mkhome dir in the first position, but this will be dirty, as it will create homedir even for inexistant user.

**Comment by mvdb-christmann** [comment]
After some more investigations, I found out that pam_mkhomedir.so shipped with Debian only provides the "session" module type is provided. The referenced plugin pam_oddjob_mkhomedir.so is not shipped with Debian, so I can't use it for in the "account" section. Using it in the "session" module seems not to be working as expected with xrdp - maybe because of a race condition?

The problem seems to me that xrdp is doing a multi-level login/authentication process: 

1. I checks whether the user can be authenticated. This seems to work as expected. My PAM configuration seems not to create a homedir in this step.
2. If the authentication is okay, it xrdp starts a session. Somewhere in this step, my PAM creates a homedir, but obviously AFTER VNC was started and is complaining it can't write the password hash file:

`can't write vnc password hash file - /home/DOMAIN/testuser/.vnc/sesman_testuser_passwd''`

**Comment by antoinetran** [comment]
Can you write you full PAM? (with dependencies if necessary).

**Comment by mvdb-christmann** [comment]
Please find the files at pastepin (basically they are debian standard files).

[xrdp-sesman](http://pastebin.ca/3391499)
[common-auth](http://pastebin.ca/3391530)
[common-account](http://pastebin.ca/3391495)
[common-session](http://pastebin.ca/3391534)
[common-password](http://pastebin.ca/3391535)

**Comment by antoinetran** [comment]
Hi, I know it's been a while, but you can try
```
#%PAM-1.0
auth required    pam_mkhomedir.so umask=0027
@include common-auth
account required    pam_mkhomedir.so umask=0027
@include common-account
session required    pam_mkhomedir.so umask=0027
@include common-session
password required    pam_mkhomedir.so umask=0027
@include common-password
```

**Comment by jay-hankins** [comment]
I am continuing to have this issue on CentOS 7 using SSSD to authenticate against LDAP (AD). The user does not have a home directory. It's supposed to be created by pam_oddjob_mkhomedir but no combination of PAM modules has worked for me (even copying ones that function correctly, like gdm-password or sshd).

Are there any updates on this?

**Comment by joeknock90** [comment]
I'm using sssd to authenticate to AD and I'm having the same issue on Fedora 25.

**Comment by antigl0w** [comment]
I am using sssd setup by realmd to auth with AD on CentOS Linux release 7.3.1611 and am having the same issue

**Comment by mattboston** [comment]
Any update on this issue?  Also using CentOS7 with SSSD tied to Active Directory and having issues with home directory creation.
